// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDAX9wUm582dTQhwUt2jP6yzDotlF9N_A',
    appId: '1:596680793489:web:942e54bac9e9f36fd8ce30',
    messagingSenderId: '596680793489',
    projectId: 'carrecommendationapp-c6e94',
    authDomain: 'carrecommendationapp-c6e94.firebaseapp.com',
    storageBucket: 'carrecommendationapp-c6e94.firebasestorage.app',
    measurementId: 'G-Y1DE59V4LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiw-N3qRGELbviKBtEs5viBmbA1WxzYCs',
    appId: '1:596680793489:android:0579a2206fca4c40d8ce30',
    messagingSenderId: '596680793489',
    projectId: 'carrecommendationapp-c6e94',
    storageBucket: 'carrecommendationapp-c6e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz35O4xPfD015yBkLLraMGNHkvF1l0vSs',
    appId: '1:596680793489:ios:496968686904be1ad8ce30',
    messagingSenderId: '596680793489',
    projectId: 'carrecommendationapp-c6e94',
    storageBucket: 'carrecommendationapp-c6e94.firebasestorage.app',
    iosBundleId: 'com.example.carRecommendationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz35O4xPfD015yBkLLraMGNHkvF1l0vSs',
    appId: '1:596680793489:ios:496968686904be1ad8ce30',
    messagingSenderId: '596680793489',
    projectId: 'carrecommendationapp-c6e94',
    storageBucket: 'carrecommendationapp-c6e94.firebasestorage.app',
    iosBundleId: 'com.example.carRecommendationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDAX9wUm582dTQhwUt2jP6yzDotlF9N_A',
    appId: '1:596680793489:web:e5d900993892dc8ad8ce30',
    messagingSenderId: '596680793489',
    projectId: 'carrecommendationapp-c6e94',
    authDomain: 'carrecommendationapp-c6e94.firebaseapp.com',
    storageBucket: 'carrecommendationapp-c6e94.firebasestorage.app',
    measurementId: 'G-S8MS5PJMR8',
  );

}